### ISSUE TITLE
Pause State

### ISSUE THREAD

**Issue by ketexon** [rh5140/srs-team-bug#42]
New state in the board that represents nothing happening
# Code

Either pauses or does not pause current animations (including the mid-turn animation)
Probably should pause mid turn, which would require modifying the board's execute code, as a coroutine is used to signal PostExecuteEvent and StartTurnEvent (both of which should not occur while paused). There is also update code in BoardObject that needs to be modified, and, of course, input code in player. Because a coroutine is used, you cannot set timescale to zero

# UI
UI for pausing with, for example, go back to map button and resume button.

**Comment by rh5140** [comment]
Doesn't match specifications but works enough for our purposes
